### ISSUE TITLE
`notion install yarn` behavior is inconsistent

### ISSUE THREAD

**Issue by benblank** [notion-cli/notion#123]
When running `notion install yarn 1`, version 1.0.0 is fetched and installed, even though newer versions are available which match that version.  This is inconsistent with `notion install yarn 1.9` and `notion install node 10`, both of which fetch and install the latest matching version.

Notion version 0.1.0 on macOS High Sierra.

**Comment by charlespierce** [comment]
This appears to have been fixed by #221 hitting the actual Yarn release index instead of our hosted copy.

**Comment by dherman** [comment]
@charlespierce Yeah but we could probably merge that PR in yarn-releases for older versions of Notion. WDYT?

**Comment by charlespierce** [comment]
Agreed, it's worth merging that (and if we continue to add new releases, doing them in the expected reverse order) to support the older versions

**Comment by charlespierce** [comment]
Merged the `yarn-releases` PR, so I believe this is fixed for all versions of Notion now.
