### ISSUE TITLE
auto-shimming

### ISSUE THREAD

**Issue by dherman** [notion-cli/notion#147]
Notion should automatically create any missing shims for binaries in a project. At the very least, running `yarn`/`npm i` should do this automatically, as well as commands like `yarn add`/`npm i <pkg>`. Creating `notion shim` was a good way to bootstrap, but for usability, it's a hole in the abstraction that requires users to understand managing shims as their job. If we reliably create shims automatically in the vast majority of cases, then users don't have to worry about it, and they have a more delightful experience—invoking a tool "just works."

As part of this task, we'll need to figure out exactly what cases we can/should auto-install shims. Maybe it's sufficient to just do it after every invocation of the package manager?

BTW another possible tactic, depending on the performance of this task, is to fork a detached child to do this work, so that returning from Notion still feels responsive. This is slightly racy so we might need to do some experiments (Is sync fast enough? Does async feel faster but without the raciness being a real issue?)

**Comment by rwjblue** [comment]
Should be fixed by https://github.com/notion-cli/notion/pull/163
