### ISSUE TITLE
fish support

### ISSUE THREAD

**Issue by dherman** [notion-cli/notion#152]
Lots of devs use the [fish](https://fishshell.com/) shell (hi @stefanpenner, hi @scalvert!). We should support it!

This will require:
- [ ] Adding a backend (`fish.rs`) to `crates/notion-core/src/shell/`, with a type `Fish` that implements `Shell`
- [ ] Adding a bootup script (`load.fish`) to `shell/unix/`, with a wrapper function `notion` to get installed at console boot time
- [ ] Adding an installer (`install.fish`) to `dev/unix/`

That last task is probably blocked on #151.

**Comment by stefanpenner** [comment]
💯
