### ISSUE TITLE
Is possible to install node paired with his respective npm version?

### ISSUE THREAD

**Issue by Icaruk** [notion-cli/notion#1542]
[This table](https://nodejs.org/en/download/releases) shows which npm version should be paired with each node version.
Is possible for Volta to install `node@16` with `npm@8` then switch to `node@20` with `npm@9`, then switch back and so on?

**Comment by robross0606** [comment]
I ran into a similar problem in that I pinned a version of `node` in a project.  Then I ran `npm install -g npm@9.8.1`.  The output even says `note: using Volta to install npm`.  However, this changed the GLOBAL global `npm` outside the pinned environment and not just the version of `npm` used by the pinned `node` version.
