### ISSUE TITLE
$NOTION_HOME is set but is not a directory on reinstall

### ISSUE THREAD

**Issue by ibraheem4** [notion-cli/notion#166]
After installing notion via curl, I deleted the folder that was created and tried reinstalling again then get this error:

    Error: $NOTION_HOME is set but is not a directory ($HOME/.notion)

Workaround would be to `mkdir $HOME/.notion` first, but it's something the tool should be able to detect I think.

**Comment by rwjblue** [comment]
The install script also installs a bit of config to your shell which is what sets `$NOTION_HOME`. Currently there is no "implode" command, so removing roughly amounts to `rm -rf ~/.notion` and updating `~/.bashrc` and/or `~/.zshrc` to remove the two lines added by the install script.

**Comment by rwjblue** [comment]
The specific error that you see is from here:

https://github.com/notion-cli/notion/blob/05b6b795a732602b7301e6b08a4353caa712c191/dev/unix/install.sh.in#L159-L163

We can likely tweak the language to be a bit more specific about what to do to clear notion from your user profile config in the second part of this message...

**Comment by ibraheem4** [comment]
Thanks for the comments @rwjblue i think most CLIs will log to the console that an entry was to `.bashrc` and/or `~/.zshrc`.  I think if we added some info that this was occurring it would be easier for developers to know how to implode.

**Comment by scalvert** [comment]
Agree with this ^

**Comment by chriskrycho** [comment]
The actual bug reported here has been resolved with updates to the installer along the way; we now cleanly install and warn if your profile still mentions Volta:

```sh
$ rm -rf ~/.volta
$ cargo build --release && ./dev/unix/build.sh && ./dev/unix/install.sh
    Finished release [optimized] target(s) in 0.68s
    Creating Volta directory tree (/Users/chris/.volta)
   Unpacking `volta` executable and shims
     Editing user profile

Warning: Your profile (/Users/chris/.config/fish/config.fish) already mentions
         Volta and has not been changed.

    Finished installation. Open a new terminal to start using Volta!
```

We also notify you that we're modifying your profile:

```sh
    Finished release [optimized] target(s) in 0.32s
    Creating Volta directory tree (/Users/chris/.volta)
   Unpacking `volta` executable and shims
     Editing user profile
    Finished installation. Open a new terminal to start using Volta!
```

I think it'd be nice if we specified *which* profile we're editing when we do that, e.g.:

```sh
     Editing user profile `/Users/chris/.bash_profile`
```
