### ISSUE TITLE
Platform specs

### ISSUE THREAD

**Issue by dherman** [notion-cli/notion#169]
Separate out the concept of _platform image_ and _platform specifier_.

  - [ ] Rename `image::` to `platform::`
  - [ ] Create `platform::Platform` type that contains the versions
  - [ ] Create `Image` type that represents a checked out platform image and contains a `Platform`
  - [ ] Stub `Platform::checkout(self) -> Fallible<Image>`

**Comment by charlespierce** [comment]
Can you got a little more in-depth about the conceptual difference between `Platform` and `Image`? Is `Platform` just the version numbers, while `Image` encapsulates the `PATH` necessary to expose those versions (and only those versions) to a script?

Does that mean that `checkout` is the operation of ensuring that all the specified versions of binaries are downloaded and unpacked in the correct places, then returning the Image that points to them?
