### ISSUE TITLE
Staging area in directory layout

### ISSUE THREAD

**Issue by dherman** [notion-cli/notion#172]
Create a concept of the _staging area_ in the Notion directory layout, where tools are unpacked and initialized to be actively used.

  - [ ] Rename `~/.notion/versions` to `~/.notion/tools/staging`
  - [x] Determine the npm version and put the default Node version under M/m/p/M/m/p
  - [x] Implement `Platform::checkout(self) -> Fallible<Image>`

Depends on:

  - [x] #169 Platform specs

**Comment by mikrostew** [comment]
Most of this has already been implemented:

* The npm version is already being determined, and the image is stored under `~/.notion/tools/image/node/M.m.p/M.m.p/`, which was implemented in #181
* `Platform::checkout(self) -> Fallible<Image>` was implemented in #232

**Comment by mikrostew** [comment]
And `~/.notion/versions/` has already been changed (in #181)

So I think there's really nothing to do for this anymore - implementing `~/.notion/tools/staging` can be done in #175.

**Comment by dherman** [comment]
Ah, you had convinced me that `tools/image` was better than `tools/staging`. Which is what #181 did. So I think this issue is officially done!
