### ISSUE TITLE
Prevent Scanning Index for Exact Versions

### ISSUE THREAD

**Issue by charlespierce** [notion-cli/notion#227]
Currently, if we have an exact version of a tool pinned in `package.json`, but that tool hasn't been downloaded to the local inventory, Notion will first fetch the index of versions for that tool, and then scan the index for a version that matches the exact version we have specified. It will then use that version to build the download URL.

This process makes sense for when we are matching a semver string, as we want to find the first version that matches, but when we already know the exact version, we should be able to shortcut and go straight to downloading. We do need to make sure to capture a 404 response and translate it into a `NoNodeVersionFoundError` / `NoYarnVersionFoundError`

**Comment by mikrostew** [comment]
Once this issues is fixed there are 3 tests created in #188 that should be un-ignored (they are marked with `ISSUE (#227)` in the code)
