### ISSUE TITLE
Notion internal error occurs for all installs

### ISSUE THREAD

**Issue by jhford** [notion-cli/notion#256]
I just used the installer from the website to install notion on my system.  When I try to run node (notion install node 11/ notion install node 11.7.0) I get:

```
$ notion -v install node 11.7.0
error: an internal error occurred

Notion is still a pre-alpha project, so we expect to run into some bugs,
but we'd love to hear about them so we can fix them!

Please feel free to reach out to us at @notionjs on Twitter or file an issue at:

    https://github.com/notion-cli/notion/issues
```

I did once briefly see (<1sec) a downloading progress indicator.  I'm not seeing any useful information in the output.  I ran the program under strace, and it looks like notion is not finding something it expects.
```
<snip>
write(2, "install: ", 9install: )                = 9
write(2, "cannot stat 'node'", 18cannot stat 'node')      = 18
<snip>
write(2, ": No such file or directory", 27: No such file or directory) = 27
write(2, "\n", 1
)  
lseek(0, 0, SEEK_CUR)                   = -1 ESPIPE (Illegal seek)
<snip>
```

I couldn't find useful logs in `~/.notion` and the `--verbose` option didn't add any useful information.  This is a Fedora 29 system with SELinux disabled.

**Comment by dschmidt** [comment]
What does `find "${NOTION_HOME}/tools/image/" -maxdepth 4` look like?

I had a bunch of similar issues when my installations had failed before https://github.com/notion-cli/notion/pull/257 was merged. It might be neccesary to wipe `${NOTION_HOME}` because the failing installations left `NOTION_HOME` in an invalid state.

**Comment by jhford** [comment]
So I installed this on a clean Fedora 29 VM and this is my installation output:
```
localhost:~ $ curl -sSLf https://get.notionjs.com | bash
    Fetching Linux installer
    Creating notion directory tree (/home/jhford/.notion)
   Unpacking notion executable and shims
     Editing user profile
    Finished installation. Open a new terminal to start using notion!
```

Running the command from your comment resulted in:
```
localhost:~ $ find "${NOTION_HOME}/tools/image/" -maxdepth 4
find: ‘/home/jhford/.notion/tools/image/’: No such file or directory
localhost:~ $ 
```

**Comment by jhford** [comment]
Also, when I try to build notion from source, I get the following error:

```
error: failed to run custom build command for `openssl-sys v0.9.24`
process didn't exit successfully: `/home/jhford/software/notion/target/debug/build/openssl-sys-d9488c5a6579f32d/build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_LIB_DIR
cargo:rerun-if-env-changed=OPENSSL_LIB_DIR
cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_INCLUDE_DIR
cargo:rerun-if-env-changed=OPENSSL_INCLUDE_DIR
cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_DIR
cargo:rerun-if-env-changed=OPENSSL_DIR
cargo:rustc-link-lib=ssl
cargo:rustc-link-lib=crypto
OPT_LEVEL = Some("0")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CC_x86_64-unknown-linux-gnu = None
CC_x86_64_unknown_linux_gnu = None
HOST_CC = None
CC = None
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CFLAGS_x86_64-unknown-linux-gnu = None
CFLAGS_x86_64_unknown_linux_gnu = None
HOST_CFLAGS = None
CFLAGS = None
DEBUG = Some("true")
running: "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-m64" "-Wall" "-Wextra" "-E" "/home/jhford/software/notion/target/debug/build/openssl-sys-1782adac4af95019/out/expando.c"
exit code: 0
cargo:rustc-cfg=osslconf="OPENSSL_NO_EC2M"
cargo:conf=OPENSSL_NO_EC2M

--- stderr
thread 'main' panicked at '

This crate is only compatible with OpenSSL 1.0.1, 1.0.2, and 1.1.0, or LibreSSL
2.5 and 2.6.0, but a different version of OpenSSL was found. The build is now
aborting due to this version mismatch.

', /home/jhford/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-sys-0.9.24/build.rs:486:9
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by dherman** [comment]
Hi @jhford! Thanks for this report. I've just merged #267 which may have fixed this issue: it adds support for OpenSSL 1.1.1. I'll be spinning a release very soon and I'll let you know when it's available if you'd like to try again. Thanks so much for the investigating you've done!

**Comment by dherman** [comment]
Oh hm, maybe that's not the core issue you're running into.

Could you try two things for me?

1. Do a clean install of notion, and then run `RUST_BACKTRACE=full NOTION_DEV=1 notion -v install node 11.7.0` and share the output here
2. Afterwards, share the output of `find "${NOTION_HOME}/tools/image/" -maxdepth 4` as @dschmidt suggested, but specifically after your failed installation occurred.

(If the output of either command is big, you can put it in a gist or use a `<details>` tag to hide it by default.)

Thanks again! :D

**Comment by jhford** [comment]
hey @dherman, hope all is well with you!

I just did the fresh installation of the new release and now am able to install node and yarn correctly, as well as building from master branch on my machine.  I guess that's the problem resolved.  I'm not sure how to install the old version to try to reproduce, but it's working now so probably not important.
