### ISSUE TITLE
npm doesn't work

### ISSUE THREAD

**Issue by darmalovan** [notion-cli/notion#261]
After installing `node`, it seems I can't use `npm`.
I'm getting "Notion error: this tool is not yet implemented" after running `npm`.
Tried `notion install npm` as well - doesn't seem to work.
Seems like a good tool, would love for your direction here.
(Working on a mac + zsh + iterm).

Thanks.

**Comment by benblank** [comment]
The bad news is that Notion 0.1.5 and earlier don't support `npm` at all.  The *good* news is that the master branch already supports both `npm` and `npx`, as will version 0.2.0 when it's released.

**Comment by robpalme** [comment]
Hello friends,

I just followed the [Understanding Notion guide](https://docs.notionjs.com/guide/understanding) and came across two of the example commands (`notion install npm` and `notion install typescript`) failing with `"not yet implemented"`.  Should the guide to also say "(not implemented yet)" next to each example command?

**Comment by mitsuhiko** [comment]
@benblank this comment suggests 0.2.0 landed with npm but my notion says npm/npx are not implemented yet.

**Comment by benblank** [comment]
@mitsuhiko I just verified that it's working with with 0.2.0 for me.  What version does `notion version` report?

**Comment by mitsuhiko** [comment]
I just realized that it works because it comes preinstalled. `notion install npm` was what threw me off.

**Comment by benblank** [comment]
Glad to hear it's working for you!
