### ISSUE TITLE
Uninstall notion

### ISSUE THREAD

**Issue by bm-stschneider** [notion-cli/notion#262]
How can I get rid of notion?

**Comment by charlespierce** [comment]
We haven't yet tackled creating an uninstaller for Notion, so to remove it manually, you'll need to do the following steps:

1. Remove the `~/.notion` directory
2. Remove the following lines from your shell profile (`~/.bash_profile`, `~/.bashrc`, or `~/.zshrc`):
    ```
    export NOTION_HOME="$HOME/.notion"
    [ -s "$NOTION_HOME/load.sh" ] && \. "$NOTION_HOME/load.sh"

    export PATH="${NOTION_HOME}/bin:$PATH"
    ```

**Comment by bm-stschneider** [comment]
Thank you.
