### ISSUE TITLE
XDG Base Directory Specification

### ISSUE THREAD

**Issue by stefanpenner** [notion-cli/notion#27]
WIP, will flesh this out later:

## What?

We should consider abiding by the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html)

This makes where notion lives on disk configurable, specifically it would abide by the following ENV variables:

* `$XDG_DATA_HOME` fallback: `$HOME/.local/share`
* `$XDG_CONFIG_HOME` fallback: `$HOME/.config`
* `$XDG_DATA_DIRS` fallback: `/usr/local/share/:/usr/share/`
* `$XDG_CONFIG_DIRS` fallback: `/etc/xdg`
* `$XDG_CACHE_HOME` fallback: `$HOME/.cache`
* `$XDG_RUNTIME_DIR` fallback see [spec]((https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html)

* more details for each are specified [here](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html)*

## Why?

* cluttering up $HOME becomes unwieldy 
* simplifies testing (we can sub-shell and simply set up the appropriate `$XDG` vars (no chroot, containers etc)
* easier to reset config / clear caches
* power users can configure to there hearts content, but no cost those who wish to rely on the fallbacks

## How

Technically, likely via the [XDG crate](https://crates.io/crates/xdg)

## Others Using XDG

Mostly just a list of whats in my `$XDG_CONFIG_HOME`, I suspect there are more.

* nvim: https://github.com/neovim/neovim/pull/3470
* asciinema
* alacritty
* git
* htop
* yarn
* fish
* fisherman

## Unresolved

Where do we put stuff in windows?

Maybe something like:

```
C:\Users\<username>\AppData\Local\notion-cli\notion\{dirs...}
```

**Comment by stefanpenner** [comment]
oops meant to be an RFC

**Comment by gibfahn** [comment]
Not sure how this becomes an RFC, but did this continue somewhere else, or would it be best to raise a new issue?

`NOTION_HOME=$XDG_CACHE_HOME/notion` lets you put most things in the cache, but there's still a `~/.notion/config.toml` (empty for me) that I don't think is configurable (e.g. to `$XDG_CONFIG_HOME/notion/config.toml`).
