### ISSUE TITLE
Notion 0.2.0 no longer supports global installs

### ISSUE THREAD

**Issue by mitsuhiko** [notion-cli/notion#272]
```
mitsuhiko at argus in ~
$ yarn global add @sentry/craft
Notion error:
Global package installs are not recommended.

Consider using `notion install` to add a package to your toolchain (see `notion help install` for more info).

mitsuhiko at argus in ~ exited 126
$ notion install @sentry/craft
thread 'main' panicked at 'not yet implemented: cannot fetch @sentry/craft', crates/notion-core/src/inventory/mod.rs:126:43
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

This used to work in older notions.

**Comment by mitsuhiko** [comment]
(Workaround is `NOTION_UNSAFE_GLOBAL=1 yarn add global @sentry/craft` in this case)

**Comment by rwjblue** [comment]
Sorry about this! Things are definitely in a non-ideal state at the moment. Ideally, we would not have released https://github.com/notion-cli/notion/pull/248 before #148. FWIW, the `notion install` flow seems _very_ close to landing in #148 though.

**Comment by rwjblue** [comment]
Notion 0.2.1 was just released to address this issue. Global installs via `yarn global add` / `npm i -g` still work in 0.2.1 while we finalize things with #247.
