### ISSUE TITLE
Consistency with version argument (-V)

### ISSUE THREAD

**Issue by thoov** [notion-cli/notion#285]
Currently notion supports -V (capital v) for "version" and -v (lowercase v) for "verbose". This seems to be inverted and goes against common norms for example:

`npm -v`, `yarn -v`,`node -v`, `ember -v`, etc all support -v as version.

This seems like a nice UX improvement to stay consistent with other tools.

**Comment by thoov** [comment]
cc @chriskrycho 

I talked with @dherman about this and he told me to add you @chriskrycho FYI

**Comment by chriskrycho** [comment]
I noticed the same thing while working on #283 and notion-cli/rfcs#30, and I'd be very happy to change it as part of #283 assuming notion-cli/rfcs#30 gets merged – or to update the Docopt strings accordingly if it doesn't. I know there are old Unix conventions around `-v`, `-vv`, etc. for log levels, but only having `--verbose` seems to be the norm for tools that have it in the Node ecosystem.

**Comment by dherman** [comment]
Agreed! This is a Node tool, so Node conventions should take precedence over old Unix conventions.
