### ISSUE TITLE
tried installing under fish, $PATH not modified

### ISSUE THREAD

**Issue by efx** [notion-cli/notion#286]
```bash
/f/e/e/ember.js (master|✔) $ curl -sSLf https://get.notionjs.com | bash
    Checking for existing Notion installation
    Fetching macOS installer
######################################################################## 100.0%
    Creating Notion directory tree (/Users/me/.notion)
   Unpacking `notion` executable and shims
     Editing user profile
    Finished installation. Open a new terminal to start using Notion!
```
I hastily entered this into my current fish shell. Command worked, but did not actually modify `~/.config/fish/config.fish`. So new shells cannot find the executable. Additionally my `$SHELL` variable is set to fish. I can jump on the discord tomorrow to trouble shoot.
https://github.com/notion-cli/notion/pull/266
https://github.com/notion-cli/notion/issues/152

**Comment by benblank** [comment]
I don't believe #266 has landed in a release, yet — it landed on the 19th, but 0.2.1 was released on the the 14th.
