### ISSUE TITLE
visible indication while fetching the public node listing

### ISSUE THREAD

**Issue by dherman** [notion-cli/notion#33]
I believe fetching the public node listing is causing a pause with no visible indication to the user. Test this hypothesis, and if it's true, we should:
- show an activity and/or progress indicator while fetching it
- possibly cache it

I'm not sure if the caching semantics works, since it could mean missing new versions. So we should think that through.

**Comment by mikrostew** [comment]
When running `notion install <version>` I am seeing a pause during this period, especially on my slow home internet.

A quick shows this is taking almost a quarter of a second for me:
```
$ time curl https://nodejs.org/dist/index.json
(...lots of JSON...)

real	0m0.705s
```

I don't think that caching makes sense for this, unless there is syntax to install multiple node versions at the same time, something like `notion install 8.9 9.4.7 lts`. In that case we should only fetch the public registry once.
