### ISSUE TITLE
Installer Updates .bashrc on MacOS, which isn't used by default

### ISSUE THREAD

**Issue by apezel** [notion-cli/notion#335]
When i follow the installation instruction i can't get notion working on MacOs 10.14.

First, ```notion install``` gives me a ```-bash: notion: command not found```

After adding an alias in my .profile : ```alias notion="/Users/home/.notion/notion"``` i can run ```notion install``` but i can't use it in a project 
```
notion activate
error: Notion shell not specified
```

**Comment by charlespierce** [comment]
Hi @apezel, that's concerning. Out of curiosity, when you ran the Notion installer (`curl -sSLf https://get.notionjs.com | bash`), did it show a line saying `Editing user profile`? It seems that your profile hasn't been correctly updated to incorporate Notion. You mention adding an alias to your `.profile`, do you have at `~/.bash_profile` or `~/.bashrc` file in your home directory that isn't being used? The installer checks for the existence of those files first, before checking for `~/.profile`, so if one of them exists but isn't being used by your terminal configuration, it's possible it got installed in the wrong place.

For reference, these are the lines that should have been added to your profile:

```bash
export NOTION_HOME="$HOME/.notion"
[ -s "$NOTION_HOME/load.sh" ] && \. "$NOTION_HOME/load.sh"

export PATH="${NOTION_HOME}/bin:$PATH"
```

**Comment by apezel** [comment]
Hello @charlespierce. Thank you for your quick reply. The installer added these lines to .bashrc. I realized that .bashrc wasn't loaded at startup of a new shell session. The MacOs Terminal seems to load .bash_profile instead. I added a ```source ~/.bashrc``` to my .bash_profile and it works perfectly now. Thank you.

**Comment by apezel** [comment]
Maybe the installer should look first for .bash_profile on MacOS platform and fallback on .bashrc if it doesn't find it ?

**Comment by charlespierce** [comment]
@apezel, Yeah, I was just looking at the code and it's currently checking `.bashrc` first, I think we can investigate the behaviors of the different OSs and come up with a plan for detecting the correct file to update.

**Comment by chriskrycho** [comment]
For reference for others who may stumble on this later, I found these two questions-and-answers extremely helpful as references (and I'm going to try to implement a fix now):

- https://apple.stackexchange.com/questions/51036/what-is-the-difference-between-bash-profile-and-bashrc
- https://unix.stackexchange.com/questions/38175/difference-between-login-shell-and-non-login-shell/46856#46856
