### ISSUE TITLE
`notion install` fails if the same version has already been installed

### ISSUE THREAD

**Issue by charlespierce** [notion-cli/notion#352]
After running `notion install <package>` once, if it is run again and the same version is found, the install will show an error on this line: https://github.com/notion-cli/notion/blob/cd37603b3f78e5bfbf4af7a40e52e7ced1463b0d/crates/notion-core/src/distro/package.rs#L168

Since the image directory is not empty. We should detect that the requested version is already installed and not attempt to re-install the same package. Related to #288

**Comment by thoov** [comment]
@charlespierce To add to this. It also returns the following error:

```
  Unpacking ember-cli-v3.9.0  [========================================] 100%
error: an internal error occurred

Notion is still a pre-alpha project, so we expect to run into some bugs,
but we'd love to hear about them so we can fix them!

Please feel free to reach out to us at @notionjs on Twitter or file an issue at:

    https://github.com/notion-cli/notion/issues

Error details written to: notion-error-2019-04-16_23_21_20.063.log
```

It would be great to reduce all of the locations where "error: an internal error occurred:" as they aren't very user friendly / helpful.

**Comment by charlespierce** [comment]
@thoov Agreed, that's tracked in #294 as the high-level issue, and I actually have a PR open right now #344 that finishes removing all the "internal errors" and replaces them with more contextual errors.
