### ISSUE TITLE
Use a friendly error instead of `unimplemented!` macro

### ISSUE THREAD

**Issue by thoov** [notion-cli/notion#359]
When running `notion uninstall node` I get the following error:

```
thread 'main' panicked at 'not yet implemented: Uninstalling Node not supported yet', crates/notion-core/src/tool/mod.rs:60:41
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

It seems like this is trying to tell me that uninstalling node is not supported. Is it possible to catch these errors and put them through the error system that @charlespierce has been working on (ie make them a little more user friendly)?

Encountered this with notion v0.3.0.

cc: @dherman @charlespierce @mikrostew

**Comment by charlespierce** [comment]
Agreed, we should remove the uses of the `unimplemented!` macro, and instead set up messages in the `ErrorDetails` enum for those cases.
