### ISSUE TITLE
Improve `notion install invalid_name` error message

### ISSUE THREAD

**Issue by thoov** [notion-cli/notion#361]
### Steps to Reproduce:

1. Run `notion install <invalid_package_name>`
2. Encounter incorrect error message

### Actual result:

```
error: an internal error occurred

Notion is still a pre-alpha project, so we expect to run into some bugs,
but we'd love to hear about them so we can fix them!

Please feel free to reach out to us at @notionjs on Twitter or file an issue at:

    https://github.com/notion-cli/notion/issues

Error details written to: notion-error-2019-04-22_11_06_00.729.log
```

### Expected result:

```
ERROR: Notion was unable to install "<invalid_package_name>".

Error details written to: <FULL_PATH_TO_FILE>/notion-error-2019-04-16_23_25_01.661.log
```
Encountered this with notion v0.3.0.

**Comment by charlespierce** [comment]
This is a good QoL improvement, thanks for suggesting it! We've already got work in #344 to get rid of the "internal errors", but adding a check to give an even more specific error in cases where the package couldn't be found is a much better UX.
