### ISSUE TITLE
Confusing error messages before installing first node or tool versions

### ISSUE THREAD

**Issue by chriskrycho** [notion-cli/notion#363]
It's fairly common to use `npm` and `yarn` to e.g. create new projects. However, if you have not yet run `notion install node` and, for yarn, also `notion install yarn`, this fails with this output:

```sh
Notion error: Could not determine Node version.

Use `notion pin node` to select a version for a project.
Use `notion install node` to select a default version.
```

The error message is technically correct… but I found it somewhat confusing (even for a fairly experienced user of Notion who has helped develop some of it!).

Two thoughts:

1. We may want to tweak this error message a little. It's *quite* terse at the moment and I think it might be helpful for the message to be *slightly* longer here, even if we keep the general terseness we've landed on to date: this is probably the most likely error for first-time users.

    ```sh
    Notion error: Could not determine Node version.

    To run any Node command, you need to set a project or default version.

      - Use `notion pin node` to select a version for a project.
      - Use `notion install node` to select a default version.
    ```

    (I'm not married to that!)

2. Perhaps our installation and setup process should prompt the user to learn *how* to start using Notion, so that if they happen to just run the installer, the installer itself tells them what to do next (without necessarily having the docs open). E.g.:

    ```sh
    $ curl -sSLf https://get.notionjs.com | bash
        Checking for existing Notion installation
        Fetching macOS installer
    ######################################################################## 100.0%
        Creating Notion directory tree (/Users/ckrycho/.notion)
       Unpacking `notion` executable and shims
         Editing user profile

        Finished installation. Open a new terminal to start using Notion!

             Tip Once you start a new terminal session, install a node version with
                 `notion install node`. For more on how to use Notion, check out
                 https://www.notionjs.com!
    ```

    (I'm not married to that, either.)

---

Also, the error report if you run `node --version` in this scenario is rather surprising:

```sh
$ node --version
Notion error: Could not determine Node version.

Use `notion pin node` to select a version for a project.
Use `notion install node` to select a default version.
```

This *looks* like there's a problem figuring out the Node version from the node command we just called; the `Notion error:` part *helps* with that but I can still see this misleading users. We may want to rephrase that first sentence a bit as well to help with that?

**Comment by charlespierce** [comment]
Good point on the error message not being as clear as it could be. I think that combined with #345, we can improve the message signficantly. Once we have pass-through working correctly, then we can more accurately say `Node is not installed` or `Node is not available`
