### ISSUE TITLE
notion install behavior surprising compared to yarn/npm

### ISSUE THREAD

**Issue by chriskrycho** [notion-cli/notion#364]
Currently `notion install` only allows a single package to be installed at a time. Users' expectation will probably be that multiple packages can be installed simultaneously, as this is the behavior of `npm install` and `yarn add` (both locally and with `--global` option). Given that we default to installing latest if a version is *not* specified, could we support this in the install command so that a user could, for example, do `notion install typescript ember-cli ts-node`?

**Comment by charlespierce** [comment]
This is interesting, and given that we are working in the Node space, I wonder if we shouldn't also update the command to support `package@version` syntax, in the same way that `npm` and `yarn` work.

**Comment by chriskrycho** [comment]
That would make sense to me. It would require an RFC I expect.

**Comment by chriskrycho** [comment]
I can write that RFC if people like—the more I use it the more I think that *should* be the behavior, but I'd like input from @dherman, @mikrostew, @rwjblue, and any other interested parties before I commit to writing that.

**Comment by mikrostew** [comment]
I think an RFC for this would be great - I like this behavior

**Comment by chriskrycho** [comment]
Consensus when I asked everybody who could make it to a meeting about release cadences was this was good; I'll write the RFC for it tomorrow. Closing this in favor of that.

**Comment by chriskrycho** [comment]
…reopening because I realize that assuming we accept such an RFC, I should close this when its implementation merges.

**Comment by chriskrycho** [comment]
Closed by #383.
