### ISSUE TITLE
`notion install` outputs version number in unexpected format

### ISSUE THREAD

**Issue by scalvert** [notion-cli/notion#373]
### Steps to Reproduce:

1. Run `notion install cowsay`
2. Observe that the version format is a hyphen-separated concatenation of the package name and the version number

### Actual Results:

The format for the version number is a hyphen-separated concatenation of the package name and the version number - `cowsay-v1.4.0`.

```
> notion install cowsay
  Fetching cowsay-v1.4.0  [========================================] 100%
npm notice created a lockfile as package-lock.json. You should commit this file.
added 9 packages from 2 contributors and audited 1535 packages in 2.954s
found 0 vulnerabilities
```

### Expected Results:

The format is an `@` separated concatenation of the package name and version number - `cowsay@1.4.0`

```
> notion install cowsay
  Fetching cowsay@1.4.0  [========================================] 100%
npm notice created a lockfile as package-lock.json. You should commit this file.
added 9 packages from 2 contributors and audited 1535 packages in 2.954s
found 0 vulnerabilities
```

**Comment by charlespierce** [comment]
Agreed, and related to #376

**Comment by scalvert** [comment]
@charlespierce should we keep this issue as a more focused issue for tracking?

**Comment by charlespierce** [comment]
They’re slightly different, so I think it makes sense to be different issues. Not a big deal though, @chriskrycho just opened #377 that closes both.
