### ISSUE TITLE
`notion install` creates a package-lock.json that cannot be found

### ISSUE THREAD

**Issue by scalvert** [notion-cli/notion#374]
### Steps to Reproduce:

1. Run `notion install cowsay`
2. Notice that the output instructs the user that a package-lock.json has been created, but this file cannot be found.

### Actual Result:

THe additional information `lockfile as package-lock.json` is included in the output, but this file cannot be found.

```
> notion install cowsay
  Fetching cowsay-v1.4.0  [========================================] 100%
npm notice created a lockfile as package-lock.json. You should commit this file.
added 9 packages from 2 contributors and audited 1535 packages in 2.954s
found 0 vulnerabilities
```

### Expected Result:

No package-lock.json is created.

```
> notion install cowsay
  Fetching cowsay-v1.4.0  [========================================] 100%
added 9 packages from 2 contributors and audited 1535 packages in 2.954s
found 0 vulnerabilities
```

I suspect this is due to notion creating a package in its own location. This is fine, but we should adjust the output so that it's not confusing.

**Comment by chriskrycho** [comment]
This raises an interesting design question: *how much (if any) of the output from tools should we be manipulating?*

One reason I think actually intercepting it (vs. documenting what you should expect) could be risky is if npm changes its output in v7, then we need to catch both; we also need to intercept and wrangle with the stdio stream from tool invocations. 🤔

**Comment by charlespierce** [comment]
We can actually clean this up really easily: When we execute `npm install` to get all the dependencies installed, we add `-q` (quiet) to the command-line flags. That sets the log-level to `warn`, so we don't see any Notices but still get the messages about how many packages were added and how many vulnerabilities were found.

**Comment by scalvert** [comment]
Well, another facet of this is that `notion` is executing a command to install what would be intended to be a global package, but is executing it without the global flag/command in order to side-step global package installation, correct? If that's the case, it's using APIs that were intended for a particular function and using them for another. I would argue that this precipitates massaging the messaging to be 'correct'. 

I do agree that this does potentially present a problem. It seems notion will need some regression testing mechanism to catch these types of things going forward.

**Comment by chriskrycho** [comment]
Agreed, to be clear – if @charlespierce's solution handles that, I think we're good on that front at least at this point.
