### ISSUE TITLE
finish the `winfolder` crate

### ISSUE THREAD

**Issue by dherman** [notion-cli/notion#39]
The `winfolder` crate only has a handful of folders that I needed for the first demo of Notion. It should be finished with the [complete set of standard Windows folders](https://msdn.microsoft.com/en-us/library/windows/desktop/dd378457.aspx).

It should probably also be extracted into its own separate repo and published to crates.io!

**Comment by charlespierce** [comment]
Is this issue still relevant? We're using `dirs` now to locate paths and don't have a `winfolder` crate any more.
