### ISSUE TITLE
exit codes

### ISSUE THREAD

**Issue by dherman** [notion-cli/notion#49]
~There should be a single module that contains a full encyclopedia of exit codes, and all the error types throughout `notion-core` and the main crate should pull their exit codes from that module.~

Thanks to @benblank we have [an exit codes RFC](https://github.com/notion-cli/rfcs/pull/20)!

**Comment by mikrostew** [comment]
This looks like what is proposed in https://github.com/notion-cli/rfcs/pull/20 - we should be able to implement this after that RFC is merged.

**Comment by dherman** [comment]
The implementation PR is #114.

**Comment by benblank** [comment]
This should have been closed when #114 was merged; oops!
