### ISSUE TITLE
resolve to a default version for each toolchain if already exists

### ISSUE THREAD

**Issue by monshi** [notion-cli/notion#64]
I installed `notion` on my mac  🎉🚀 and got so excited 💃🕺so that the first thing I did after that was to run `node -v` in the same directory and I got this error: `error: An unknown error has occurred`.
I was assuming that if there is no `package.json` or `notion` config block then `notion` will either fall back to a default version of `node` or will respect my previously installed version of `node`. By that I mean, when the notion is installed on a machine it can detect and install the global version of my installed toolchain (`node`, `yarn` ...) and set them as default versions.

If the expected behavior is not as I assumed, then maybe another option would be showing some instructions/helpful errors instead of `error: An unknown error has occurred`. I'll be happy to help fixing it as well :)

**Comment by charlespierce** [comment]
The error message part of this issue has been resolved with the error rework. The pass-through to existing tools is currently in review in #372
